#include "types.cpp"

State map1[10][10] = {
        State::Ship, State::Empty, State::Empty, State::Empty, State::Ship, State::Ship, State::Empty, State::Ship,
        State::Ship, State::Empty,
        State::Empty, State::Ship, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Ship,
        State::Empty, State::Empty, State::Ship, State::Empty, State::Ship, State::Ship, State::Empty,
        State::Empty, State::Empty, State::Ship,
        State::Empty, State::Empty, State::Empty, State::Ship, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Ship,
        State::Empty, State::Empty, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty,
        State::Ship, State::Ship, State::Ship, State::Empty, State::Ship, State::Ship, State::Ship,
        State::Ship, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty,
};

State map2[10][10] = {
        State::Ship, State::Empty, State::Empty, State::Empty, State::Ship, State::Ship, State::Empty, State::Ship,
        State::Ship, State::Empty,
        State::Empty, State::Ship, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Ship,
        State::Empty, State::Empty, State::Ship, State::Empty, State::Ship, State::Ship, State::Empty,
        State::Empty, State::Empty, State::Ship,
        State::Empty, State::Empty, State::Empty, State::Ship, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Ship,
        State::Empty, State::Empty, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty,
        State::Ship, State::Ship, State::Ship, State::Empty, State::Ship, State::Ship, State::Ship,
        State::Ship, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty, State::Empty, State::Empty,
        State::Empty, State::Empty, State::Empty, State::Empty,
};
